FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY main.go .

RUN go build -o /server main.go

FROM alpine:3.20 AS runner

WORKDIR /app

COPY --from=builder /server .

CMD ["./server"]