name: Setup NPM and Node.JS for CI/CD
description: Setup NPM and Node.js for CI/CD

runs: 
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
    
    - name: Install dependencies
      run: npm ci