name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Lint
        # working-directory es mas declarativo que hacer "cd" dentro del run, y funciona igual en los runners de Windows de la matriz
        working-directory: 12-ejercicio-cicd  # raiz del repo
        run: |
          echo "::group::Lint"
          pnpm lint:frontend
          echo "::endgroup::"

  frontend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Test"
          pnpm test:frontend
          echo "::endgroup::"

  frontend-build:
    needs: [frontend-lint, frontend-test]
    if: success()
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Build
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Build"
          pnpm build:frontend
          echo "::endgroup::"

  backend-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Lint
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Lint"
          pnpm lint:backend
          echo "::endgroup::"

  backend-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Test
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Test"
          pnpm test:backend
          echo "::endgroup::"

  backend-build:
    needs: [backend-lint, backend-test]
    if: success()
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
      - name: Smoke test
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Smoke test"
          pnpm build:backend
          echo "::endgroup::"

  frontend-test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['22', '24']
        os: [ubuntu-24.04, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm-ci-cd
        with:
          node-version: ${{ matrix.node-version }}
      - name: Smoke test frontend with matrix
        working-directory: 12-ejercicio-cicd
        run: |
          echo "::group::Smoke test"
          pnpm test:frontend
          echo "::endgroup::"