name: 05 - CI
  
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node
        uses: ./github/actions/setup-npm.yml
      
      - name: Lint
        run: |
          cd 12-current
          
  